name = "web-scan-workflow-worker"
main = "index.ts"
compatibility_date = "2025-12-01"
compatibility_flags = ["nodejs_compat"]

[[workflows]]
name = "web-scan-workflow"
binding = "SCAN_WORKFLOW"
class_name = "ScanWorkflow"

[vars]
FIREBASE_PROJECT_ID = "..."
FIREBASE_DATABASE_ID = "(default)"
FIREBASE_API_KEY = "..."
INTERNAL_SECRET = "..."
