import type { ToolInputMode } from '@/types/tool-checks';

export type ToolCategorySlug =
  | 'seo'
  | 'ki'
  | 'traffic-markt'
  | 'local'
  | 'content'
  | 'social'
  | 'anzeigen'
  | 'ki-pr'
  | 'berichte'
  | 'security-dsgvo'
  | 'performance-technik';

export type ToolEngine =
  | 'single-page-seo'
  | 'pagespeed'
  | 'security'
  | 'meta'
  | 'robots'
  | 'sitemap'
  | 'ai-visibility'
  | 'keyword-local'
  | 'text-utility'
  | 'url-provider'
  | 'keyword-provider'
  | 'full-audit'
  | 'reporting';

export type ToolStatus = 'live' | 'provider' | 'audit' | 'planned';

export type ToolIconName =
  | 'search'
  | 'zap'
  | 'shield'
  | 'fileText'
  | 'terminal'
  | 'sitemap'
  | 'brain'
  | 'target'
  | 'link'
  | 'chart'
  | 'map'
  | 'megaphone'
  | 'users'
  | 'eye'
  | 'lock'
  | 'check';

export type ToolCategory = {
  slug: ToolCategorySlug;
  title: string;
  navTitle: string;
  headline: string;
  description: string;
  seoDescription: string;
  icon: ToolIconName;
  priority: number;
};

export type ToolSlug = string;

export type ToolPage = {
  slug: ToolSlug;
  title: string;
  shortTitle: string;
  headline: string;
  description: string;
  seoDescription: string;
  inputMode: ToolInputMode;
  inputLabel?: string;
  placeholder: string;
  buttonLabel: string;
  categorySlug: ToolCategorySlug;
  category: string;
  icon: ToolIconName;
  engine: ToolEngine;
  status: ToolStatus;
  checks: string[];
  related: ToolSlug[];
};

export const TOOL_CATEGORIES: ToolCategory[] = [
  {
    slug: 'seo',
    title: 'SEO Tools',
    navTitle: 'SEO',
    headline: 'SEO Tools für einzelne Seiten, Crawls und Rankings',
    description: 'Onpage, Technik, Indexierung, Keywords, interne Links, Backlinks und Site Audits als eigene Einstiege.',
    seoDescription: 'SEO Tools für Onpage SEO, technische Audits, Keywords, Sitemaps, Robots.txt, interne Links, Backlinks und Indexierung.',
    icon: 'search',
    priority: 0.98,
  },
  {
    slug: 'ki',
    title: 'KI & AI Visibility Tools',
    navTitle: 'KI',
    headline: 'KI Sichtbarkeit, LLM-Crawler und Answer Engine Optimierung',
    description: 'Prüfe AI-Crawler-Zugriff, Entitäten, strukturierte Daten und Lesbarkeit für KI-Suchsysteme.',
    seoDescription: 'KI SEO Tools für AI Visibility, ChatGPT Sichtbarkeit, LLM-Crawler, AI Overviews und Answer Engine Optimierung.',
    icon: 'brain',
    priority: 0.96,
  },
  {
    slug: 'traffic-markt',
    title: 'Traffic & Markt Tools',
    navTitle: 'Traffic & Markt',
    headline: 'Traffic, Markt und Wettbewerber getrennt vom Crawl analysieren',
    description: 'Domain-Checks, Wettbewerber, Marktüberblick, Share of Voice und Opportunity-Finder als eigene Datenstrecken.',
    seoDescription: 'Traffic und Markt Tools für Wettbewerber, Domain Overview, Share of Voice, Marktchancen und Content-Gaps.',
    icon: 'chart',
    priority: 0.9,
  },
  {
    slug: 'local',
    title: 'Local SEO Tools',
    navTitle: 'Local',
    headline: 'Local SEO, Google Business Profile und Standortseiten',
    description: 'Lokale Sichtbarkeit, NAP-Konsistenz, Bewertungen, Standortseiten und Maps-nahe SEO-Prozesse.',
    seoDescription: 'Local SEO Tools für Google Business Profile, NAP-Konsistenz, Bewertungen, Citations und lokale Landingpages.',
    icon: 'map',
    priority: 0.88,
  },
  {
    slug: 'content',
    title: 'Content Tools',
    navTitle: 'Content',
    headline: 'Content, Briefings, Snippets und Textqualität',
    description: 'Content Audits, Briefings, Title-Ideen, Meta Descriptions, Lesbarkeit, Wortzähler und Themencluster.',
    seoDescription: 'Content SEO Tools für Content Audits, Briefings, Title Generator, Meta Descriptions, Lesbarkeit und Topic Cluster.',
    icon: 'fileText',
    priority: 0.9,
  },
  {
    slug: 'social',
    title: 'Social Tools',
    navTitle: 'Social',
    headline: 'Social Previews, Open Graph und Content Distribution',
    description: 'Social Snippets, Open-Graph Checks, UTM-Struktur, Social Reports und kanalfähige Content-Ideen.',
    seoDescription: 'Social Tools für Open Graph, Social Preview, UTM Builder, Social Content Planung und Social Reports.',
    icon: 'users',
    priority: 0.78,
  },
  {
    slug: 'anzeigen',
    title: 'Anzeigen Tools',
    navTitle: 'Anzeigen',
    headline: 'Ads, PPC und Landingpage-Qualität getrennt prüfen',
    description: 'Google Ads Keywords, Ad Copy, PPC Wettbewerber und Landingpage Readiness ohne technischen Full Crawl.',
    seoDescription: 'Anzeigen Tools für Google Ads Keywords, PPC Wettbewerber, Ad Copy, Landingpage Qualität und Conversion Readiness.',
    icon: 'megaphone',
    priority: 0.78,
  },
  {
    slug: 'ki-pr',
    title: 'KI-PR Tools',
    navTitle: 'KI-PR',
    headline: 'KI-PR, Quellenautorität und Brand Mentions',
    description: 'Bereite Marken, Quellen, Zitate und PR-Themen für AI Search und klassische Pressearbeit vor.',
    seoDescription: 'KI-PR Tools für Brand Mentions, Quellenautorität, Citation Readiness, AI PR und Outreach Planung.',
    icon: 'eye',
    priority: 0.76,
  },
  {
    slug: 'berichte',
    title: 'Berichte & Agentur Tools',
    navTitle: 'Berichte',
    headline: 'Berichte, Evidence, White Label und Kundenportale',
    description: 'Reports, Exporte, Evidence-Screenshots, Monitoring, Team-Workflows und Agentur-Abrechnung als eigene Seiten.',
    seoDescription: 'Berichte und Agentur Tools für SEO Reports, White Label, Kundenportale, Monitoring Reports und Evidence Screenshots.',
    icon: 'check',
    priority: 0.84,
  },
  {
    slug: 'security-dsgvo',
    title: 'Security & DSGVO Tools',
    navTitle: 'Security & DSGVO',
    headline: 'Security, Datenschutz und Compliance als eigener USP',
    description: 'Header, HTTPS, Cookies, Datenschutz, Barrierefreiheit und rechtliche Website-Risiken als separate Checks.',
    seoDescription: 'Security und DSGVO Tools für Security Header, HTTPS, Cookie Checks, Datenschutz, Accessibility und Compliance.',
    icon: 'shield',
    priority: 0.86,
  },
  {
    slug: 'performance-technik',
    title: 'Performance & Technik Tools',
    navTitle: 'Performance & Technik',
    headline: 'Performance, Rendering, Core Web Vitals und technische Checks',
    description: 'PageSpeed, Core-Web-Vitals-nahe Checks, Redirects, Rendering, Statuscodes und technische Health Checks.',
    seoDescription: 'Performance und Technik Tools für PageSpeed, Core Web Vitals, Redirects, Rendering und technische Website Checks.',
    icon: 'zap',
    priority: 0.86,
  },
];

const categoryTitleBySlug = new Map(TOOL_CATEGORIES.map((category) => [category.slug, category.title]));

const TOOL_DEFINITIONS: Array<Omit<ToolPage, 'category'>> = [
  {
    slug: 'seo-checker',
    title: 'SEO Checker',
    shortTitle: 'SEO Check',
    headline: 'SEO Checker für einzelne Seiten',
    description: 'Prüft Title, Description, H1, Canonical, Robots und grundlegende Onpage-Signale für genau eine URL.',
    seoDescription: 'Kostenloser SEO Checker für einzelne Seiten: Meta Title, Description, H1, Canonical, Robots und Onpage-Basics ohne Full Crawl prüfen.',
    inputMode: 'url',
    placeholder: 'https://deine-domain.de/landingpage',
    buttonLabel: 'SEO Check starten',
    categorySlug: 'seo',
    icon: 'search',
    engine: 'single-page-seo',
    status: 'live',
    checks: ['Meta-Daten', 'H1-Struktur', 'Canonical', 'Indexierbarkeit'],
    related: ['on-page-seo-checker', 'meta-title-checker', 'technical-seo-audit'],
  },
  {
    slug: 'technical-seo-audit',
    title: 'Technical SEO Audit',
    shortTitle: 'Technical SEO',
    headline: 'Technical SEO Audit für ganze Websites',
    description: 'Führt technische SEO-Signale, Statuscodes, Canonicals, interne Links und Crawl-Fehler in einem Deep Audit zusammen.',
    seoDescription: 'Technical SEO Audit Tool für Statuscodes, Canonicals, interne Links, Crawl Fehler, Indexierung und technische Website-Qualität.',
    inputMode: 'url',
    placeholder: 'https://deine-domain.de',
    buttonLabel: 'Audit vorbereiten',
    categorySlug: 'seo',
    icon: 'terminal',
    engine: 'full-audit',
    status: 'audit',
    checks: ['Crawl-Budget', 'Statuscodes', 'Canonicals', 'Interne Links'],
    related: ['seo-checker', 'indexability-checker', 'broken-link-checker'],
  },
  {
    slug: 'site-audit',
    title: 'Site Audit',
    shortTitle: 'Site Audit',
    headline: 'Site Audit mit SEO, Technik und Prioritäten',
    description: 'Der volle Website Analyzer Crawl für SEO, Performance, Security, DSGVO, Accessibility und AI Visibility.',
    seoDescription: 'Site Audit Tool für SEO, Performance, Security, DSGVO, Accessibility, AI Visibility und priorisierte Website-Maßnahmen.',
    inputMode: 'url',
    placeholder: 'https://deine-domain.de',
    buttonLabel: 'Site Audit starten',
    categorySlug: 'seo',
    icon: 'search',
    engine: 'full-audit',
    status: 'audit',
    checks: ['Full Crawl', 'Prioritäten', 'Evidence', 'Reports'],
    related: ['technical-seo-audit', 'seo-report-generator', 'monitoring-report'],
  },
  {
    slug: 'on-page-seo-checker',
    title: 'On Page SEO Checker',
    shortTitle: 'On Page',
    headline: 'On Page SEO einer URL prüfen',
    description: 'Prüft Meta-Daten, Überschriften, Canonical, Indexierbarkeit und sichtbare Textbasis für eine Seite.',
    seoDescription: 'On Page SEO Checker für Meta-Daten, H1, Canonical, Indexierbarkeit und sichtbare Textbasis einer einzelnen URL.',
    inputMode: 'url',
    placeholder: 'https://deine-domain.de/seite',
    buttonLabel: 'On Page prüfen',
    categorySlug: 'seo',
    icon: 'fileText',
    engine: 'single-page-seo',
    status: 'live',
    checks: ['Title', 'Description', 'H1', 'Textbasis'],
    related: ['seo-checker', 'meta-title-checker', 'readability-checker'],
  },
  {
    slug: 'keyword-checker',
    title: 'Keyword Checker',
    shortTitle: 'Keyword',
    headline: 'Keyword-Idee schnell einschätzen',
    description: 'Analysiert Suchphrase, Intent-Hinweise, Longtail-Potenzial und Content-Format ohne externe SERP-Kosten.',
    seoDescription: 'Keyword Checker für erste SEO-Ideen: Suchphrase, Intent-Hinweise, Longtail-Potenzial und Content-Format schnell einschätzen.',
    inputMode: 'keyword',
    placeholder: 'seo audit agentur',
    buttonLabel: 'Keyword prüfen',
    categorySlug: 'seo',
    icon: 'target',
    engine: 'keyword-local',
    status: 'live',
    checks: ['Intent-Hinweise', 'Longtail-Potenzial', 'Content-Format', 'Keyword-Länge'],
    related: ['keyword-gap-checker', 'content-brief-generator', 'serp-preview-tool'],
  },
  {
    slug: 'keyword-gap-checker',
    title: 'Keyword Gap Checker',
    shortTitle: 'Keyword Gap',
    headline: 'Keyword-Lücken gegen Wettbewerber finden',
    description: 'Bereitet Keyword-Gap-Analysen als eigene Datenstrecke vor, statt sie mit technischen Crawls zu vermischen.',
    seoDescription: 'Keyword Gap Checker für Wettbewerber-Keywords, Content-Lücken und SEO-Potenziale als separate Analyse.',
    inputMode: 'keyword',
    placeholder: 'dein keyword oder themencluster',
    buttonLabel: 'Gap vorbereiten',
    categorySlug: 'seo',
    icon: 'target',
    engine: 'keyword-provider',
    status: 'provider',
    checks: ['Wettbewerberdaten', 'SERP-Daten', 'Lücken', 'Prioritäten'],
    related: ['competitor-checker', 'content-gap-checker', 'market-overview'],
  },
  {
    slug: 'serp-preview-tool',
    title: 'SERP Preview Tool',
    shortTitle: 'SERP Preview',
    headline: 'Google Snippet Vorschau für Title und Description',
    description: 'Prüft Title und Description einer URL und zeigt, ob die Snippet-Basis stimmt.',
    seoDescription: 'SERP Preview Tool für Meta Title, Meta Description und Google Snippet Vorschau einer einzelnen URL.',
    inputMode: 'url',
    placeholder: 'https://deine-domain.de/angebot',
    buttonLabel: 'Snippet prüfen',
    categorySlug: 'seo',
    icon: 'fileText',
    engine: 'meta',
    status: 'live',
    checks: ['Title-Länge', 'Description-Länge', 'Open Graph', 'Canonical'],
    related: ['meta-title-checker', 'meta-description-generator', 'seo-checker'],
  },
  {
    slug: 'meta-title-checker',
    title: 'Meta Title & Description Checker',
    shortTitle: 'Meta Check',
    headline: 'Meta Title und Description prüfen',
    description: 'Prüft Länge, Vorhandensein und SERP-Basisdaten einer einzelnen Seite.',
    seoDescription: 'Meta Title Checker und Meta Description Checker: Title-Länge, Description-Länge und SERP-Basics für eine URL testen.',
    inputMode: 'url',
    placeholder: 'https://deine-domain.de/angebot',
    buttonLabel: 'Meta Tags prüfen',
    categorySlug: 'seo',
    icon: 'fileText',
    engine: 'meta',
    status: 'live',
    checks: ['Title-Länge', 'Description-Länge', 'SERP-Basics', 'Canonical'],
    related: ['serp-preview-tool', 'seo-checker', 'content-brief-generator'],
  },
  {
    slug: 'robots-txt-checker',
    title: 'Robots.txt Checker',
    shortTitle: 'Robots.txt',
    headline: 'Robots.txt und Crawler-Zugriff testen',
    description: 'Liest die robots.txt einer Domain und erkennt Sitemaps, Disallow-Regeln und AI-Crawler-Hinweise.',
    seoDescription: 'Robots.txt Checker: robots.txt finden, Disallow-Regeln, Sitemap-Hinweise und AI-Crawler-Signale schnell prüfen.',
    inputMode: 'url',
    placeholder: 'https://deine-domain.de',
    buttonLabel: 'Robots.txt prüfen',
    categorySlug: 'seo',
    icon: 'terminal',
    engine: 'robots',
    status: 'live',
    checks: ['Robots.txt Status', 'Disallow-Regeln', 'Sitemaps', 'AI-Crawler'],
    related: ['sitemap-checker', 'ai-crawler-checker', 'indexability-checker'],
  },
  {
    slug: 'sitemap-checker',
    title: 'XML Sitemap Checker',
    shortTitle: 'Sitemap',
    headline: 'Sitemap.xml einer Domain prüfen',
    description: 'Findet die Standard-Sitemap, zählt URL- oder Sitemap-Einträge und prüft XML-Grundlagen.',
    seoDescription: 'XML Sitemap Checker: sitemap.xml finden, Status prüfen und URL- oder Sitemap-Einträge einer Domain zählen.',
    inputMode: 'url',
    placeholder: 'https://deine-domain.de',
    buttonLabel: 'Sitemap prüfen',
    categorySlug: 'seo',
    icon: 'sitemap',
    engine: 'sitemap',
    status: 'live',
    checks: ['Sitemap Status', 'URL-Zähler', 'Sitemap-Index', 'XML-Basischeck'],
    related: ['robots-txt-checker', 'technical-seo-audit', 'indexability-checker'],
  },
  {
    slug: 'canonical-checker',
    title: 'Canonical Checker',
    shortTitle: 'Canonical',
    headline: 'Canonical Tag einer URL prüfen',
    description: 'Prüft, ob eine Seite ein Canonical besitzt und ob die Basis-Signale für Indexierung stimmen.',
    seoDescription: 'Canonical Checker für einzelne URLs: Canonical Tag, Meta Robots und Onpage-Basis ohne Full Crawl prüfen.',
    inputMode: 'url',
    placeholder: 'https://deine-domain.de/seite',
    buttonLabel: 'Canonical prüfen',
    categorySlug: 'seo',
    icon: 'link',
    engine: 'single-page-seo',
    status: 'live',
    checks: ['Canonical', 'Meta Robots', 'HTTP Status', 'Title'],
    related: ['indexability-checker', 'duplicate-content-checker', 'seo-checker'],
  },
  {
    slug: 'indexability-checker',
    title: 'Indexability Checker',
    shortTitle: 'Indexability',
    headline: 'Indexierbarkeit einer Seite prüfen',
    description: 'Prüft HTTP Status, Meta Robots, Canonical und Crawl-Hinweise für eine einzelne URL.',
    seoDescription: 'Indexability Checker für HTTP Status, Meta Robots, Canonical und Indexierungsrisiken einer einzelnen URL.',
    inputMode: 'url',
    placeholder: 'https://deine-domain.de/seite',
    buttonLabel: 'Indexierung prüfen',
    categorySlug: 'seo',
    icon: 'check',
    engine: 'single-page-seo',
    status: 'live',
    checks: ['Statuscode', 'Noindex', 'Canonical', 'Robots'],
    related: ['robots-txt-checker', 'canonical-checker', 'sitemap-checker'],
  },
  {
    slug: 'broken-link-checker',
    title: 'Broken Link Checker',
    shortTitle: 'Broken Links',
    headline: 'Broken Links im Full Audit finden',
    description: 'Sammelt defekte interne und externe Links über Crawl-Batches und Evidence-Daten.',
    seoDescription: 'Broken Link Checker für defekte interne und externe Links, Statuscodes und Evidence im Website Audit.',
    inputMode: 'url',
    placeholder: 'https://deine-domain.de',
    buttonLabel: 'Broken-Link Audit vorbereiten',
    categorySlug: 'seo',
    icon: 'link',
    engine: 'full-audit',
    status: 'audit',
    checks: ['Interne Links', 'Externe Links', 'Statuscodes', 'Evidence'],
    related: ['internal-link-checker', 'redirect-chain-checker', 'technical-seo-audit'],
  },
  {
    slug: 'internal-link-checker',
    title: 'Internal Link Checker',
    shortTitle: 'Internal Links',
    headline: 'Interne Verlinkung und Linkjuice prüfen',
    description: 'Bereitet interne Link-Audits, Ankertexte, Linktiefe und verwaiste Seiten als eigene Analyse vor.',
    seoDescription: 'Internal Link Checker für interne Verlinkung, Ankertexte, Linktiefe, verwaiste Seiten und Linkstruktur.',
    inputMode: 'url',
    placeholder: 'https://deine-domain.de',
    buttonLabel: 'Link-Audit vorbereiten',
    categorySlug: 'seo',
    icon: 'link',
    engine: 'full-audit',
    status: 'audit',
    checks: ['Linktiefe', 'Ankertexte', 'Orphan Pages', 'Linkgraph'],
    related: ['broken-link-checker', 'site-audit', 'seo-report-generator'],
  },
  {
    slug: 'duplicate-content-checker',
    title: 'Duplicate Content Checker',
    shortTitle: 'Duplicate Content',
    headline: 'Duplicate Content im Crawl erkennen',
    description: 'Findet doppelte Titel, Descriptions, Content-Fingerprints und Canonical-Konflikte im Site Audit.',
    seoDescription: 'Duplicate Content Checker für doppelte Titel, Descriptions, Canonicals und Content-Fingerprints.',
    inputMode: 'url',
    placeholder: 'https://deine-domain.de',
    buttonLabel: 'Duplicate Audit vorbereiten',
    categorySlug: 'seo',
    icon: 'fileText',
    engine: 'full-audit',
    status: 'audit',
    checks: ['Titel-Duplikate', 'Descriptions', 'Canonicals', 'Fingerprints'],
    related: ['canonical-checker', 'technical-seo-audit', 'content-audit'],
  },
  {
    slug: 'structured-data-checker',
    title: 'Structured Data Checker',
    shortTitle: 'Schema Check',
    headline: 'JSON-LD und strukturierte Daten prüfen',
    description: 'Zählt JSON-LD-Blöcke und zeigt, ob eine einzelne Seite maschinenlesbare Struktur liefert.',
    seoDescription: 'Structured Data Checker für JSON-LD, Schema.org Signale und maschinenlesbare Struktur einer URL.',
    inputMode: 'url',
    placeholder: 'https://deine-domain.de/seite',
    buttonLabel: 'Schema prüfen',
    categorySlug: 'seo',
    icon: 'fileText',
    engine: 'ai-visibility',
    status: 'live',
    checks: ['JSON-LD', 'H1', 'Textbasis', 'Noindex'],
    related: ['ai-visibility-checker', 'entity-checker', 'seo-checker'],
  },
  {
    slug: 'hreflang-checker',
    title: 'Hreflang Checker',
    shortTitle: 'Hreflang',
    headline: 'Hreflang und internationale SEO vorbereiten',
    description: 'Hreflang braucht Seitenbeziehungen und wird deshalb sauber als Crawl-gestützter Audit vorbereitet.',
    seoDescription: 'Hreflang Checker für internationale SEO, Sprachversionen, Canonicals und Hreflang-Konflikte.',
    inputMode: 'url',
    placeholder: 'https://deine-domain.de',
    buttonLabel: 'Hreflang Audit vorbereiten',
    categorySlug: 'seo',
    icon: 'sitemap',
    engine: 'full-audit',
    status: 'audit',
    checks: ['Sprachversionen', 'Return Tags', 'Canonicals', 'Konflikte'],
    related: ['technical-seo-audit', 'sitemap-checker', 'canonical-checker'],
  },
  {
    slug: 'backlink-checker',
    title: 'Backlink Checker',
    shortTitle: 'Backlinks',
    headline: 'Backlink-Check ohne Website-Crawl vorbereiten',
    description: 'Validiert die Domain und trennt Backlink-Daten sauber vom technischen Full Audit.',
    seoDescription: 'Backlink Checker als eigene SEO-Unterseite: Domain prüfen und Backlink-Analyse separat vom Website-Crawl starten.',
    inputMode: 'url',
    placeholder: 'https://deine-domain.de',
    buttonLabel: 'Backlink Check starten',
    categorySlug: 'seo',
    icon: 'link',
    engine: 'url-provider',
    status: 'provider',
    checks: ['Domain-Validierung', 'Provider-Status', 'Authority-Fokus', 'Kein Full Crawl'],
    related: ['link-building-tool', 'competitor-backlink-checker', 'seo-checker'],
  },
  {
    slug: 'link-building-tool',
    title: 'Link Building Tool',
    shortTitle: 'Link Building',
    headline: 'Linkbuilding Opportunities vorbereiten',
    description: 'Trennt Outreach, Backlink-Providerdaten und Aufgabenlisten vom technischen Website-Crawl.',
    seoDescription: 'Link Building Tool für Outreach, Backlink Opportunities, Wettbewerberlinks und Aufgabenlisten.',
    inputMode: 'url',
    placeholder: 'https://deine-domain.de',
    buttonLabel: 'Linkbuilding vorbereiten',
    categorySlug: 'seo',
    icon: 'link',
    engine: 'url-provider',
    status: 'provider',
    checks: ['Outreach', 'Backlink-Gaps', 'Listen', 'Aufgaben'],
    related: ['backlink-checker', 'competitor-backlink-checker', 'ai-pr-visibility-checker'],
  },
  {
    slug: 'ai-visibility-checker',
    title: 'AI Visibility Checker',
    shortTitle: 'AI Visibility',
    headline: 'AI Visibility einer Seite testen',
    description: 'Prüft, ob eine Seite für AI Search lesbar wirkt: Robots, Noindex, strukturierte Daten, H1 und Textbasis.',
    seoDescription: 'AI Visibility Checker: Robots, Noindex, strukturierte Daten, H1 und Textbasis für AI Search und LLM-Crawler prüfen.',
    inputMode: 'url',
    placeholder: 'https://deine-domain.de/ratgeber',
    buttonLabel: 'AI Visibility prüfen',
    categorySlug: 'ki',
    icon: 'brain',
    engine: 'ai-visibility',
    status: 'live',
    checks: ['AI-Crawler-Zugriff', 'Noindex', 'JSON-LD', 'Textbasis'],
    related: ['chatgpt-visibility-checker', 'ai-crawler-checker', 'entity-checker'],
  },
  {
    slug: 'chatgpt-visibility-checker',
    title: 'ChatGPT Visibility Checker',
    shortTitle: 'ChatGPT Check',
    headline: 'ChatGPT Sichtbarkeit technisch vorbereiten',
    description: 'Prüft AI-Crawler-Zugriff, strukturierte Daten und Textbasis als technische Grundlage für LLM-Sichtbarkeit.',
    seoDescription: 'ChatGPT Visibility Checker für AI-Crawler, Robots.txt, strukturierte Daten und maschinenlesbare Textbasis.',
    inputMode: 'url',
    placeholder: 'https://deine-domain.de/ratgeber',
    buttonLabel: 'ChatGPT Basis prüfen',
    categorySlug: 'ki',
    icon: 'brain',
    engine: 'ai-visibility',
    status: 'live',
    checks: ['GPTBot-Hinweise', 'Robots', 'JSON-LD', 'Textbasis'],
    related: ['ai-visibility-checker', 'llm-robots-checker', 'answer-engine-optimization'],
  },
  {
    slug: 'llm-robots-checker',
    title: 'LLM Robots Checker',
    shortTitle: 'LLM Robots',
    headline: 'LLM-Crawler in robots.txt prüfen',
    description: 'Erkennt bekannte AI-Crawler-Regeln und Root-Blockaden in der robots.txt einer Domain.',
    seoDescription: 'LLM Robots Checker für GPTBot, ChatGPT-User, ClaudeBot, PerplexityBot und Google-Extended in robots.txt.',
    inputMode: 'url',
    placeholder: 'https://deine-domain.de',
    buttonLabel: 'LLM Robots prüfen',
    categorySlug: 'ki',
    icon: 'terminal',
    engine: 'robots',
    status: 'live',
    checks: ['GPTBot', 'ClaudeBot', 'PerplexityBot', 'Google-Extended'],
    related: ['robots-txt-checker', 'ai-crawler-checker', 'ai-visibility-checker'],
  },
  {
    slug: 'ai-crawler-checker',
    title: 'AI Crawler Checker',
    shortTitle: 'AI Crawler',
    headline: 'AI-Crawler Zugriff einer Domain prüfen',
    description: 'Kombiniert robots.txt und Seitenbasis, um unbeabsichtigte Blockaden für AI Search zu erkennen.',
    seoDescription: 'AI Crawler Checker für robots.txt, AI Bot Blockaden, Noindex und technische AI Visibility Grundlagen.',
    inputMode: 'url',
    placeholder: 'https://deine-domain.de',
    buttonLabel: 'AI-Crawler prüfen',
    categorySlug: 'ki',
    icon: 'brain',
    engine: 'ai-visibility',
    status: 'live',
    checks: ['Robots', 'AI Bots', 'Noindex', 'Textbasis'],
    related: ['llm-robots-checker', 'chatgpt-visibility-checker', 'robots-txt-checker'],
  },
  {
    slug: 'answer-engine-optimization',
    title: 'Answer Engine Optimization Tool',
    shortTitle: 'AEO Tool',
    headline: 'Answer Engine Optimization für Inhalte planen',
    description: 'Bewertet Fragen-Intent, Entitäten, strukturierte Daten und Textbasis als Vorbereitung für AI Answers.',
    seoDescription: 'Answer Engine Optimization Tool für AI Search, Fragen-Intent, Entitäten, strukturierte Daten und Content Briefings.',
    inputMode: 'keyword',
    placeholder: 'wie funktioniert technisches seo',
    buttonLabel: 'AEO Idee prüfen',
    categorySlug: 'ki',
    icon: 'brain',
    engine: 'keyword-local',
    status: 'live',
    checks: ['Fragen-Intent', 'Content-Format', 'Longtail', 'Briefing'],
    related: ['ai-content-brief-generator', 'entity-checker', 'ai-snippet-checker'],
  },
  {
    slug: 'entity-checker',
    title: 'Entity Checker',
    shortTitle: 'Entity Check',
    headline: 'Entitäten und Themenklarheit prüfen',
    description: 'Bereitet Entity- und Brand-Signale für Knowledge Graph, AI Search und strukturierte Inhalte vor.',
    seoDescription: 'Entity Checker für Marken, Themen, strukturierte Daten und Entity SEO im Kontext von AI Search.',
    inputMode: 'text',
    placeholder: 'Füge einen Absatz, eine Leistungsbeschreibung oder ein Brand-Profil ein',
    buttonLabel: 'Entitäten einschätzen',
    categorySlug: 'ki',
    icon: 'brain',
    engine: 'text-utility',
    status: 'live',
    checks: ['Textbasis', 'Begriffe', 'Satzstruktur', 'Snippet-Potenzial'],
    related: ['ai-visibility-checker', 'brand-entity-checker', 'structured-data-checker'],
  },
  {
    slug: 'google-ai-overview-checker',
    title: 'Google AI Overview Checker',
    shortTitle: 'AI Overview',
    headline: 'AI Overview Potenzial separat analysieren',
    description: 'Bereitet Keyword- und SERP-Daten für AI Overview Tracking vor, ohne technische Crawls zu starten.',
    seoDescription: 'Google AI Overview Checker für Keywords, SERP Features und AI Overview Potenzial als eigene Datenstrecke.',
    inputMode: 'keyword',
    placeholder: 'beste seo audit software',
    buttonLabel: 'AI Overview vorbereiten',
    categorySlug: 'ki',
    icon: 'eye',
    engine: 'keyword-provider',
    status: 'provider',
    checks: ['SERP Features', 'AI Overview', 'Keyworddaten', 'Quellen'],
    related: ['answer-engine-optimization', 'keyword-checker', 'ai-pr-visibility-checker'],
  },
  {
    slug: 'ai-content-brief-generator',
    title: 'AI Content Brief Generator',
    shortTitle: 'AI Brief',
    headline: 'AI Content Brief als eigene Content-Strecke',
    description: 'Erstellt lokale Briefing-Hinweise aus Keyword und Intent; echte SERP-Daten können später als Provider angebunden werden.',
    seoDescription: 'AI Content Brief Generator für Keyword, Intent, Content-Format, Struktur und SEO-Briefing.',
    inputMode: 'keyword',
    placeholder: 'local seo für restaurants',
    buttonLabel: 'Briefing erstellen',
    categorySlug: 'ki',
    icon: 'brain',
    engine: 'keyword-local',
    status: 'live',
    checks: ['Intent', 'Format', 'Longtail', 'Struktur'],
    related: ['content-brief-generator', 'topic-cluster-planner', 'answer-engine-optimization'],
  },
  {
    slug: 'ai-snippet-checker',
    title: 'AI Snippet Checker',
    shortTitle: 'AI Snippet',
    headline: 'Snippet-Tauglichkeit für AI Answers prüfen',
    description: 'Prüft kurze Texte auf Länge, Satzstruktur und Antwortklarheit für AI- und Such-Snippets.',
    seoDescription: 'AI Snippet Checker für kurze Antworten, Satzstruktur, Textlänge und AI Search Snippet Potenzial.',
    inputMode: 'text',
    placeholder: 'Füge die Antwort oder den Absatz ein, der in AI Search erscheinen soll',
    buttonLabel: 'Snippet prüfen',
    categorySlug: 'ki',
    icon: 'fileText',
    engine: 'text-utility',
    status: 'live',
    checks: ['Antwortlänge', 'Satzlänge', 'Lesbarkeit', 'Klarheit'],
    related: ['answer-engine-optimization', 'readability-checker', 'meta-description-generator'],
  },
  {
    slug: 'competitor-checker',
    title: 'Competitor Checker',
    shortTitle: 'Competitors',
    headline: 'Wettbewerber als eigene Marktanalyse prüfen',
    description: 'Validiert Domain oder Thema und bereitet Wettbewerberdaten getrennt vom technischen Site Audit vor.',
    seoDescription: 'Competitor Checker für SEO Wettbewerber, Marktanalyse, Domainvergleich und Opportunity-Finder.',
    inputMode: 'url',
    placeholder: 'https://dein-wettbewerber.de',
    buttonLabel: 'Wettbewerber vorbereiten',
    categorySlug: 'traffic-markt',
    icon: 'chart',
    engine: 'url-provider',
    status: 'provider',
    checks: ['Domain', 'Markt', 'SERP-Daten', 'Opportunities'],
    related: ['market-overview', 'competitor-gap-tool', 'domain-overview'],
  },
  {
    slug: 'domain-overview',
    title: 'Domain Overview',
    shortTitle: 'Domain Overview',
    headline: 'Domain Overview für SEO, Markt und Risiken',
    description: 'Baut eine eigenständige Domain-Sicht für Traffic, Authority, Keywords und technische Signale auf.',
    seoDescription: 'Domain Overview Tool für SEO, Traffic, Wettbewerber, Backlinks, Keywords und technische Domain-Signale.',
    inputMode: 'url',
    placeholder: 'https://deine-domain.de',
    buttonLabel: 'Domain vorbereiten',
    categorySlug: 'traffic-markt',
    icon: 'chart',
    engine: 'url-provider',
    status: 'provider',
    checks: ['Domain', 'Keywords', 'Traffic', 'Authority'],
    related: ['traffic-estimator', 'backlink-checker', 'site-audit'],
  },
  {
    slug: 'traffic-estimator',
    title: 'Traffic Estimator',
    shortTitle: 'Traffic',
    headline: 'Traffic-Schätzung getrennt vom Crawl vorbereiten',
    description: 'Trafficdaten brauchen Such- oder Clickstream-Provider und werden sauber als eigener Marktkanal behandelt.',
    seoDescription: 'Traffic Estimator für Domain Traffic, organische Reichweite, Wettbewerber und Markttrends.',
    inputMode: 'url',
    placeholder: 'https://deine-domain.de',
    buttonLabel: 'Traffic vorbereiten',
    categorySlug: 'traffic-markt',
    icon: 'chart',
    engine: 'url-provider',
    status: 'provider',
    checks: ['Trafficdaten', 'Trend', 'Kanal', 'Wettbewerb'],
    related: ['market-overview', 'share-of-voice', 'domain-overview'],
  },
  {
    slug: 'market-overview',
    title: 'Market Overview Tool',
    shortTitle: 'Market Overview',
    headline: 'Marktüberblick für Themen und Domains',
    description: 'Legt Markt-, Wettbewerbs- und Nachfrageanalysen als separate Toolstrecke an.',
    seoDescription: 'Market Overview Tool für Marktgröße, Wettbewerber, Nachfrage, Traffic und Chancen.',
    inputMode: 'keyword',
    placeholder: 'seo software für agenturen',
    buttonLabel: 'Markt vorbereiten',
    categorySlug: 'traffic-markt',
    icon: 'chart',
    engine: 'keyword-provider',
    status: 'provider',
    checks: ['Nachfrage', 'Wettbewerber', 'Chancen', 'Trends'],
    related: ['competitor-checker', 'traffic-estimator', 'keyword-gap-checker'],
  },
  {
    slug: 'share-of-voice',
    title: 'Share of Voice Checker',
    shortTitle: 'Share of Voice',
    headline: 'Share of Voice für Keyword-Sets vorbereiten',
    description: 'Sichtbarkeit über Keyword-Sets braucht Rankingdaten und bleibt deshalb ein eigener Datenbereich.',
    seoDescription: 'Share of Voice Checker für Ranking-Sets, Wettbewerber, Sichtbarkeit und Marktanteile in SERPs.',
    inputMode: 'keyword',
    placeholder: 'dein keyword-set oder themencluster',
    buttonLabel: 'Share vorbereiten',
    categorySlug: 'traffic-markt',
    icon: 'chart',
    engine: 'keyword-provider',
    status: 'provider',
    checks: ['Rankings', 'Keyword-Sets', 'Wettbewerber', 'Sichtbarkeit'],
    related: ['rank-tracker', 'market-overview', 'competitor-gap-tool'],
  },
  {
    slug: 'competitor-gap-tool',
    title: 'Competitor Gap Tool',
    shortTitle: 'Competitor Gap',
    headline: 'Wettbewerbslücken für SEO und Content finden',
    description: 'Plant Gap-Analysen für Keywords, Seiten, Backlinks und Content getrennt von technischen Scans.',
    seoDescription: 'Competitor Gap Tool für Keyword Gaps, Content Gaps, Backlink Gaps und Wettbewerberchancen.',
    inputMode: 'keyword',
    placeholder: 'deine branche oder hauptkeyword',
    buttonLabel: 'Gap vorbereiten',
    categorySlug: 'traffic-markt',
    icon: 'target',
    engine: 'keyword-provider',
    status: 'provider',
    checks: ['Keyword-Gap', 'Content-Gap', 'Backlink-Gap', 'Prioritäten'],
    related: ['keyword-gap-checker', 'content-gap-checker', 'competitor-backlink-checker'],
  },
  {
    slug: 'competitor-backlink-checker',
    title: 'Competitor Backlink Checker',
    shortTitle: 'Competitor Links',
    headline: 'Backlinks von Wettbewerbern getrennt analysieren',
    description: 'Bereitet Link-Gap-Daten und Outreach-Chancen als Backlink-Add-on statt als Crawl-Funktion vor.',
    seoDescription: 'Competitor Backlink Checker für Link Gaps, Backlink Opportunities und Wettbewerberdomains.',
    inputMode: 'url',
    placeholder: 'https://wettbewerber.de',
    buttonLabel: 'Backlink Gap vorbereiten',
    categorySlug: 'traffic-markt',
    icon: 'link',
    engine: 'url-provider',
    status: 'provider',
    checks: ['Backlink-Gap', 'Domains', 'Authority', 'Outreach'],
    related: ['backlink-checker', 'link-building-tool', 'competitor-gap-tool'],
  },
  {
    slug: 'rank-tracker',
    title: 'Rank Tracker',
    shortTitle: 'Rank Tracking',
    headline: 'Rankings und Keywords fortlaufend überwachen',
    description: 'Rank-Tracking ist ein eigenes Keyword-Budget und soll nicht mit einmaligen Audits verwechselt werden.',
    seoDescription: 'Rank Tracker für SEO Rankings, Keyword Monitoring, Wettbewerber und Sichtbarkeitsveränderungen.',
    inputMode: 'keyword',
    placeholder: 'seo audit software',
    buttonLabel: 'Ranking vorbereiten',
    categorySlug: 'traffic-markt',
    icon: 'chart',
    engine: 'keyword-provider',
    status: 'provider',
    checks: ['Keywords', 'Positionen', 'Historie', 'Wettbewerber'],
    related: ['share-of-voice', 'keyword-checker', 'monitoring-report'],
  },
  {
    slug: 'local-seo-checker',
    title: 'Local SEO Checker',
    shortTitle: 'Local SEO',
    headline: 'Local SEO für Standortseiten prüfen',
    description: 'Prüft eine lokale Landingpage auf Onpage-Basis und bereitet Maps- und Listingdaten separat vor.',
    seoDescription: 'Local SEO Checker für Standortseiten, lokale Keywords, NAP, Google Business Profile und Maps-Sichtbarkeit.',
    inputMode: 'url',
    placeholder: 'https://deine-domain.de/standort/berlin',
    buttonLabel: 'Local SEO prüfen',
    categorySlug: 'local',
    icon: 'map',
    engine: 'single-page-seo',
    status: 'live',
    checks: ['Landingpage', 'Title', 'H1', 'Indexierung'],
    related: ['google-business-profile-checker', 'nap-consistency-checker', 'service-area-page-checker'],
  },
  {
    slug: 'google-business-profile-checker',
    title: 'Google Business Profile Checker',
    shortTitle: 'GBP Check',
    headline: 'Google Business Profile als eigene Local-Strecke',
    description: 'Bereitet Profil-, Kategorien-, Review- und Maps-Daten getrennt vom Website-Crawl vor.',
    seoDescription: 'Google Business Profile Checker für Local SEO, Kategorien, Reviews, Profile und Maps-Sichtbarkeit.',
    inputMode: 'keyword',
    placeholder: 'firma + stadt',
    buttonLabel: 'GBP vorbereiten',
    categorySlug: 'local',
    icon: 'map',
    engine: 'keyword-provider',
    status: 'provider',
    checks: ['Profil', 'Kategorien', 'Reviews', 'Maps'],
    related: ['local-seo-checker', 'review-monitoring', 'local-rank-tracker'],
  },
  {
    slug: 'nap-consistency-checker',
    title: 'NAP Consistency Checker',
    shortTitle: 'NAP Check',
    headline: 'Name, Adresse und Telefon konsistent halten',
    description: 'Prüft eingegebene NAP-Daten lokal und bereitet Citation-Provider für echte Verzeichnisdaten vor.',
    seoDescription: 'NAP Consistency Checker für Name, Adresse, Telefonnummer, Citations und Local SEO Konsistenz.',
    inputMode: 'text',
    placeholder: 'Name, Adresse, Telefonnummer und Website eintragen',
    buttonLabel: 'NAP Text prüfen',
    categorySlug: 'local',
    icon: 'map',
    engine: 'text-utility',
    status: 'live',
    checks: ['Name', 'Adresse', 'Telefon', 'Website'],
    related: ['local-citation-checker', 'google-business-profile-checker', 'local-seo-checker'],
  },
  {
    slug: 'local-citation-checker',
    title: 'Local Citation Checker',
    shortTitle: 'Citations',
    headline: 'Local Citations und Verzeichnisse vorbereiten',
    description: 'Citation-Daten brauchen Verzeichnis-Provider und werden sauber als Local Add-on getrennt.',
    seoDescription: 'Local Citation Checker für Branchenverzeichnisse, NAP, Local SEO und Standortdaten.',
    inputMode: 'keyword',
    placeholder: 'firmenname + stadt',
    buttonLabel: 'Citations vorbereiten',
    categorySlug: 'local',
    icon: 'map',
    engine: 'keyword-provider',
    status: 'provider',
    checks: ['Verzeichnisse', 'NAP', 'Duplikate', 'Konsistenz'],
    related: ['nap-consistency-checker', 'local-seo-checker', 'google-business-profile-checker'],
  },
  {
    slug: 'review-monitoring',
    title: 'Review Monitoring',
    shortTitle: 'Reviews',
    headline: 'Bewertungen für Local SEO überwachen',
    description: 'Review-Daten werden als eigene Monitoring-Strecke vorbereitet und nicht mit Crawls vermischt.',
    seoDescription: 'Review Monitoring Tool für Bewertungen, Reputation, Google Business Profile und Local SEO Signale.',
    inputMode: 'keyword',
    placeholder: 'firma oder standort',
    buttonLabel: 'Review Monitoring vorbereiten',
    categorySlug: 'local',
    icon: 'map',
    engine: 'keyword-provider',
    status: 'provider',
    checks: ['Bewertungen', 'Sterne', 'Antworten', 'Trends'],
    related: ['google-business-profile-checker', 'local-rank-tracker', 'monitoring-report'],
  },
  {
    slug: 'local-rank-tracker',
    title: 'Local Rank Tracker',
    shortTitle: 'Local Ranks',
    headline: 'Lokale Rankings und Maps-Sichtbarkeit tracken',
    description: 'Lokale Rankings brauchen Standort- und Keyword-Sets und sind ein eigener Plan-Bereich.',
    seoDescription: 'Local Rank Tracker für Google Maps, lokale Keywords, Standort-Rankings und Local SEO Monitoring.',
    inputMode: 'keyword',
    placeholder: 'zahnarzt berlin mitte',
    buttonLabel: 'Local Ranking vorbereiten',
    categorySlug: 'local',
    icon: 'chart',
    engine: 'keyword-provider',
    status: 'provider',
    checks: ['Standort', 'Keyword', 'Maps', 'Historie'],
    related: ['local-seo-checker', 'share-of-voice', 'monitoring-report'],
  },
  {
    slug: 'service-area-page-checker',
    title: 'Service Area Page Checker',
    shortTitle: 'Service Areas',
    headline: 'Service- und Standortseiten einzeln testen',
    description: 'Prüft Title, Description, H1 und Indexierbarkeit für lokale Service-Seiten.',
    seoDescription: 'Service Area Page Checker für lokale Landingpages, Standortseiten, Service Pages und Onpage SEO.',
    inputMode: 'url',
    placeholder: 'https://deine-domain.de/leistungen/berlin',
    buttonLabel: 'Service-Seite prüfen',
    categorySlug: 'local',
    icon: 'map',
    engine: 'single-page-seo',
    status: 'live',
    checks: ['Title', 'H1', 'Canonical', 'Indexierung'],
    related: ['local-seo-checker', 'nap-consistency-checker', 'content-brief-generator'],
  },
  {
    slug: 'content-audit',
    title: 'Content Audit',
    shortTitle: 'Content Audit',
    headline: 'Content Audit für Seiten und Themen',
    description: 'Prüft eine URL auf Title, Description, Textbasis und strukturierte Signale; volle Content-Inventare laufen im Audit.',
    seoDescription: 'Content Audit Tool für Textbasis, Meta-Daten, Struktur, Content-Qualität und Themenabdeckung.',
    inputMode: 'url',
    placeholder: 'https://deine-domain.de/blog/beitrag',
    buttonLabel: 'Content prüfen',
    categorySlug: 'content',
    icon: 'fileText',
    engine: 'ai-visibility',
    status: 'live',
    checks: ['Textbasis', 'Title', 'H1', 'JSON-LD'],
    related: ['readability-checker', 'content-brief-generator', 'content-gap-checker'],
  },
  {
    slug: 'content-brief-generator',
    title: 'Content Brief Generator',
    shortTitle: 'Brief Generator',
    headline: 'SEO Content Brief aus Keyword und Intent',
    description: 'Erstellt lokale Briefing-Hinweise für Format, Intent und Struktur ohne externe SERP-Kosten.',
    seoDescription: 'Content Brief Generator für SEO Briefings, Keyword Intent, Content Struktur und Themenplanung.',
    inputMode: 'keyword',
    placeholder: 'website audit checklist',
    buttonLabel: 'Brief erstellen',
    categorySlug: 'content',
    icon: 'fileText',
    engine: 'keyword-local',
    status: 'live',
    checks: ['Intent', 'Format', 'Longtail', 'Struktur'],
    related: ['ai-content-brief-generator', 'topic-cluster-planner', 'keyword-checker'],
  },
  {
    slug: 'ai-title-generator',
    title: 'AI Title Generator',
    shortTitle: 'Title Generator',
    headline: 'Title-Ideen für SEO, Social und Ads erzeugen',
    description: 'Nutzt lokale Heuristiken für schnelle Title-Ideen; echte AI-Generierung kann später als Add-on laufen.',
    seoDescription: 'AI Title Generator für SEO Titles, Blog Headlines, Social Posts und Anzeigenideen.',
    inputMode: 'keyword',
    placeholder: 'seo audit für kleine unternehmen',
    buttonLabel: 'Title-Ideen erzeugen',
    categorySlug: 'content',
    icon: 'fileText',
    engine: 'keyword-local',
    status: 'live',
    checks: ['Keyword', 'Intent', 'Title-Format', 'Snippet'],
    related: ['meta-title-checker', 'meta-description-generator', 'serp-preview-tool'],
  },
  {
    slug: 'meta-description-generator',
    title: 'Meta Description Generator',
    shortTitle: 'Description Generator',
    headline: 'Meta Description für Seiten vorbereiten',
    description: 'Prüft Textlänge und erstellt strukturierte Hinweise für klickstarke Snippets.',
    seoDescription: 'Meta Description Generator für SEO Snippets, Klickrate, SERP Preview und Seitenbeschreibungen.',
    inputMode: 'text',
    placeholder: 'Füge Seiteninhalt oder Angebotstext ein',
    buttonLabel: 'Description vorbereiten',
    categorySlug: 'content',
    icon: 'fileText',
    engine: 'text-utility',
    status: 'live',
    checks: ['Textlänge', 'Satzstruktur', 'Snippet', 'Klarheit'],
    related: ['serp-preview-tool', 'meta-title-checker', 'ai-snippet-checker'],
  },
  {
    slug: 'word-counter',
    title: 'Word Counter',
    shortTitle: 'Word Counter',
    headline: 'Wortzahl, Zeichen und Satzstruktur prüfen',
    description: 'Zählt Worte, Zeichen und Sätze für Content, Snippets, Briefings und AI-Antworten.',
    seoDescription: 'Word Counter Tool für Wortzahl, Zeichen, Sätze, Textlänge und Content-Qualität.',
    inputMode: 'text',
    placeholder: 'Füge deinen Text ein',
    buttonLabel: 'Text zählen',
    categorySlug: 'content',
    icon: 'fileText',
    engine: 'text-utility',
    status: 'live',
    checks: ['Wörter', 'Zeichen', 'Sätze', 'Lesbarkeit'],
    related: ['readability-checker', 'ai-snippet-checker', 'content-audit'],
  },
  {
    slug: 'readability-checker',
    title: 'Readability Checker',
    shortTitle: 'Readability',
    headline: 'Lesbarkeit und Satzlänge prüfen',
    description: 'Bewertet Wortzahl, Satzlänge und Textstruktur als schneller Content-Qualitätscheck.',
    seoDescription: 'Readability Checker für Lesbarkeit, Satzlänge, Wortzahl, Content-Qualität und SEO Texte.',
    inputMode: 'text',
    placeholder: 'Füge einen Absatz oder ganzen Text ein',
    buttonLabel: 'Lesbarkeit prüfen',
    categorySlug: 'content',
    icon: 'fileText',
    engine: 'text-utility',
    status: 'live',
    checks: ['Satzlänge', 'Wörter', 'Struktur', 'Klarheit'],
    related: ['word-counter', 'content-audit', 'paragraph-rewriter'],
  },
  {
    slug: 'paragraph-rewriter',
    title: 'Paragraph Rewriter',
    shortTitle: 'Rewriter',
    headline: 'Absatz verbessern und SEO-klarer machen',
    description: 'Analysiert den Text lokal und gibt Hinweise für Klarheit, Kürze und bessere Struktur.',
    seoDescription: 'Paragraph Rewriter für klare Abschnitte, bessere Lesbarkeit, SEO Texte und Content Optimierung.',
    inputMode: 'text',
    placeholder: 'Füge den Absatz ein, der verbessert werden soll',
    buttonLabel: 'Absatz analysieren',
    categorySlug: 'content',
    icon: 'fileText',
    engine: 'text-utility',
    status: 'live',
    checks: ['Klarheit', 'Satzlänge', 'Struktur', 'Nächster Schritt'],
    related: ['readability-checker', 'ai-title-generator', 'content-brief-generator'],
  },
  {
    slug: 'content-gap-checker',
    title: 'Content Gap Checker',
    shortTitle: 'Content Gap',
    headline: 'Content-Lücken gegen Wettbewerber vorbereiten',
    description: 'Content-Gaps brauchen SERP- und Wettbewerberdaten und werden als eigenständige Marktanalyse behandelt.',
    seoDescription: 'Content Gap Checker für Wettbewerberinhalte, Themenlücken, Keyword-Gaps und Content Chancen.',
    inputMode: 'keyword',
    placeholder: 'thema oder hauptkeyword',
    buttonLabel: 'Content Gap vorbereiten',
    categorySlug: 'content',
    icon: 'target',
    engine: 'keyword-provider',
    status: 'provider',
    checks: ['Wettbewerber', 'SERP', 'Themen', 'Gaps'],
    related: ['competitor-gap-tool', 'keyword-gap-checker', 'topic-cluster-planner'],
  },
  {
    slug: 'topic-cluster-planner',
    title: 'Topic Cluster Planner',
    shortTitle: 'Topic Cluster',
    headline: 'Topic Cluster aus einem Hauptthema planen',
    description: 'Strukturiert Themen, Unterseiten und interne Verlinkung als Grundlage für SEO-Cluster.',
    seoDescription: 'Topic Cluster Planner für SEO Themencluster, Pillar Pages, Unterseiten und interne Verlinkung.',
    inputMode: 'keyword',
    placeholder: 'website relaunch seo',
    buttonLabel: 'Cluster planen',
    categorySlug: 'content',
    icon: 'sitemap',
    engine: 'keyword-local',
    status: 'live',
    checks: ['Pillar-Idee', 'Unterseiten', 'Intent', 'Interne Links'],
    related: ['internal-link-checker', 'content-brief-generator', 'answer-engine-optimization'],
  },
  {
    slug: 'plagiarism-checker',
    title: 'Plagiarism Checker',
    shortTitle: 'Plagiarism',
    headline: 'Plagiatsprüfung als Provider-Strecke vorbereiten',
    description: 'Echte Plagiatsprüfung braucht Webindex-Provider und wird nicht als Fake-Textcheck verkauft.',
    seoDescription: 'Plagiarism Checker für Content Originalität, Webindex Vergleich und Content Qualität.',
    inputMode: 'text',
    placeholder: 'Füge den zu prüfenden Text ein',
    buttonLabel: 'Plagiat vorbereiten',
    categorySlug: 'content',
    icon: 'fileText',
    engine: 'url-provider',
    status: 'provider',
    checks: ['Originalität', 'Webindex', 'Quellen', 'Content Risiko'],
    related: ['content-audit', 'readability-checker', 'duplicate-content-checker'],
  },
  {
    slug: 'open-graph-checker',
    title: 'Open Graph Checker',
    shortTitle: 'Open Graph',
    headline: 'Open Graph Daten einer URL prüfen',
    description: 'Prüft Social Title, Description und Meta-Basis für geteilte Links.',
    seoDescription: 'Open Graph Checker für og:title, og:description, Social Preview und Link Sharing.',
    inputMode: 'url',
    placeholder: 'https://deine-domain.de/seite',
    buttonLabel: 'Open Graph prüfen',
    categorySlug: 'social',
    icon: 'users',
    engine: 'meta',
    status: 'live',
    checks: ['OG Title', 'OG Description', 'Title', 'Description'],
    related: ['social-preview-checker', 'serp-preview-tool', 'utm-builder'],
  },
  {
    slug: 'social-preview-checker',
    title: 'Social Preview Checker',
    shortTitle: 'Social Preview',
    headline: 'Social Preview für geteilte URLs testen',
    description: 'Prüft, ob eine Seite ausreichend Meta- und Open-Graph-Daten für Social Shares liefert.',
    seoDescription: 'Social Preview Checker für LinkedIn, Facebook, Messenger, Open Graph und Social Snippets.',
    inputMode: 'url',
    placeholder: 'https://deine-domain.de/blog',
    buttonLabel: 'Social Preview prüfen',
    categorySlug: 'social',
    icon: 'users',
    engine: 'meta',
    status: 'live',
    checks: ['Open Graph', 'Title', 'Description', 'Canonical'],
    related: ['open-graph-checker', 'linkedin-post-generator', 'social-content-planner'],
  },
  {
    slug: 'utm-builder',
    title: 'UTM Builder',
    shortTitle: 'UTM Builder',
    headline: 'UTM-Struktur für Kampagnen vorbereiten',
    description: 'Validiert Ziel-URL und trennt Kampagnentracking sauber von SEO-Crawls.',
    seoDescription: 'UTM Builder für Kampagnen URLs, Source, Medium, Campaign und Social Tracking.',
    inputMode: 'url',
    placeholder: 'https://deine-domain.de/angebot',
    buttonLabel: 'URL prüfen',
    categorySlug: 'social',
    icon: 'link',
    engine: 'url-provider',
    status: 'provider',
    checks: ['Ziel-URL', 'Campaign', 'Medium', 'Tracking'],
    related: ['social-preview-checker', 'ads-landing-page-checker', 'conversion-readiness-checker'],
  },
  {
    slug: 'social-content-planner',
    title: 'Social Content Planner',
    shortTitle: 'Social Planner',
    headline: 'Social Content aus Themen und Seiten planen',
    description: 'Plant Social-Formate und Distribution aus Keyword, Thema oder URL als eigene Content-Strecke.',
    seoDescription: 'Social Content Planner für Posts, Themen, Kampagnen, Distribution und Social Content Ideen.',
    inputMode: 'keyword',
    placeholder: 'seo audit checkliste',
    buttonLabel: 'Social Ideen planen',
    categorySlug: 'social',
    icon: 'users',
    engine: 'keyword-local',
    status: 'live',
    checks: ['Thema', 'Format', 'Intent', 'Post-Ideen'],
    related: ['linkedin-post-generator', 'instagram-caption-generator', 'topic-cluster-planner'],
  },
  {
    slug: 'linkedin-post-generator',
    title: 'LinkedIn Post Generator',
    shortTitle: 'LinkedIn',
    headline: 'LinkedIn Post-Ideen aus einem Thema erzeugen',
    description: 'Erzeugt lokale Strukturhinweise für LinkedIn Hooks, Post-Format und CTA.',
    seoDescription: 'LinkedIn Post Generator für Hooks, Post Ideen, Content Distribution und B2B Social Content.',
    inputMode: 'keyword',
    placeholder: 'warum technische seo audits geld sparen',
    buttonLabel: 'LinkedIn Ideen erzeugen',
    categorySlug: 'social',
    icon: 'users',
    engine: 'keyword-local',
    status: 'live',
    checks: ['Hook', 'Format', 'CTA', 'Intent'],
    related: ['social-content-planner', 'ai-title-generator', 'content-brief-generator'],
  },
  {
    slug: 'instagram-caption-generator',
    title: 'Instagram Caption Generator',
    shortTitle: 'Instagram',
    headline: 'Instagram Captions für Kampagnen vorbereiten',
    description: 'Plant kurze Caption-Varianten und Formatideen auf Basis eines Themas.',
    seoDescription: 'Instagram Caption Generator für Social Captions, Hooks, Kampagnen und Content Ideen.',
    inputMode: 'keyword',
    placeholder: 'website relaunch tipps',
    buttonLabel: 'Captions planen',
    categorySlug: 'social',
    icon: 'users',
    engine: 'keyword-local',
    status: 'live',
    checks: ['Hook', 'Kurztext', 'Format', 'CTA'],
    related: ['social-content-planner', 'linkedin-post-generator', 'ai-title-generator'],
  },
  {
    slug: 'social-report',
    title: 'Social Report',
    shortTitle: 'Social Report',
    headline: 'Social Reports für Agenturen vorbereiten',
    description: 'Social-Kennzahlen werden als Report-Strecke vorbereitet und mit SEO-Reports kombinierbar gemacht.',
    seoDescription: 'Social Report Tool für Agenturen, Kampagnen, Social KPIs und kombinierte Kundenreports.',
    inputMode: 'url',
    placeholder: 'https://deine-domain.de',
    buttonLabel: 'Social Report vorbereiten',
    categorySlug: 'social',
    icon: 'users',
    engine: 'reporting',
    status: 'audit',
    checks: ['KPIs', 'Kampagnen', 'Report', 'Kundenansicht'],
    related: ['client-report-generator', 'monitoring-report', 'utm-builder'],
  },
  {
    slug: 'ads-landing-page-checker',
    title: 'Ads Landing Page Checker',
    shortTitle: 'Ads Landingpage',
    headline: 'Landingpage für Anzeigen separat prüfen',
    description: 'Prüft Title, Description, Erreichbarkeit und Performance-Basis ohne Full Crawl.',
    seoDescription: 'Ads Landing Page Checker für PPC Landingpages, Erreichbarkeit, Meta-Daten, Speed und Conversion Readiness.',
    inputMode: 'url',
    placeholder: 'https://deine-domain.de/angebot',
    buttonLabel: 'Landingpage prüfen',
    categorySlug: 'anzeigen',
    icon: 'megaphone',
    engine: 'single-page-seo',
    status: 'live',
    checks: ['Status', 'Title', 'H1', 'Indexierung'],
    related: ['landing-page-quality-checker', 'conversion-readiness-checker', 'pagespeed-test'],
  },
  {
    slug: 'google-ads-keyword-checker',
    title: 'Google Ads Keyword Checker',
    shortTitle: 'Ads Keywords',
    headline: 'Google Ads Keyword-Ideen vorbereiten',
    description: 'Bewertet Intent und Format lokal; echte CPC- und Volumendaten brauchen Ads-Provider.',
    seoDescription: 'Google Ads Keyword Checker für PPC Keywords, Intent, CPC Providerdaten und Kampagnenplanung.',
    inputMode: 'keyword',
    placeholder: 'seo audit buchen',
    buttonLabel: 'Ads Keyword prüfen',
    categorySlug: 'anzeigen',
    icon: 'target',
    engine: 'keyword-local',
    status: 'live',
    checks: ['Intent', 'Commercial Fit', 'Longtail', 'Format'],
    related: ['ad-copy-generator', 'ppc-competitor-checker', 'ads-landing-page-checker'],
  },
  {
    slug: 'ppc-competitor-checker',
    title: 'PPC Competitor Checker',
    shortTitle: 'PPC Competitors',
    headline: 'PPC Wettbewerber als eigene Datenstrecke',
    description: 'PPC-Daten und Anzeigenhistorie brauchen Provider und werden nicht mit SEO-Crawls vermischt.',
    seoDescription: 'PPC Competitor Checker für Google Ads Wettbewerber, Anzeigen, Keywords und Landingpages.',
    inputMode: 'keyword',
    placeholder: 'branche oder keyword',
    buttonLabel: 'PPC vorbereiten',
    categorySlug: 'anzeigen',
    icon: 'megaphone',
    engine: 'keyword-provider',
    status: 'provider',
    checks: ['Anzeigen', 'Keywords', 'Landingpages', 'Wettbewerber'],
    related: ['google-ads-keyword-checker', 'ad-copy-generator', 'market-overview'],
  },
  {
    slug: 'ad-copy-generator',
    title: 'Ad Copy Generator',
    shortTitle: 'Ad Copy',
    headline: 'Anzeigentexte aus Keyword und Angebot planen',
    description: 'Erstellt lokale Strukturhinweise für Headlines, Nutzenversprechen und CTA.',
    seoDescription: 'Ad Copy Generator für Google Ads Headlines, Descriptions, Nutzenversprechen und CTA Ideen.',
    inputMode: 'keyword',
    placeholder: 'website audit für agenturen',
    buttonLabel: 'Ad Copy planen',
    categorySlug: 'anzeigen',
    icon: 'megaphone',
    engine: 'keyword-local',
    status: 'live',
    checks: ['Headline', 'Intent', 'CTA', 'Angebot'],
    related: ['google-ads-keyword-checker', 'landing-page-quality-checker', 'ai-title-generator'],
  },
  {
    slug: 'landing-page-quality-checker',
    title: 'Landing Page Quality Checker',
    shortTitle: 'Landing Quality',
    headline: 'Landingpage-Qualität für Ads und SEO prüfen',
    description: 'Prüft Onpage-Basis, Meta-Daten und technische Signale einer einzelnen Landingpage.',
    seoDescription: 'Landing Page Quality Checker für Anzeigen, SEO, Meta-Daten, H1, Indexierung und Performance-Basis.',
    inputMode: 'url',
    placeholder: 'https://deine-domain.de/landingpage',
    buttonLabel: 'Qualität prüfen',
    categorySlug: 'anzeigen',
    icon: 'check',
    engine: 'single-page-seo',
    status: 'live',
    checks: ['Title', 'Description', 'H1', 'Canonical'],
    related: ['conversion-readiness-checker', 'pagespeed-test', 'ads-landing-page-checker'],
  },
  {
    slug: 'conversion-readiness-checker',
    title: 'Conversion Readiness Checker',
    shortTitle: 'Conversion',
    headline: 'Conversion Readiness einer Seite einschätzen',
    description: 'Prüft Erreichbarkeit, Onpage-Basis und Performance-Signale als Vorstufe für CRO-Audits.',
    seoDescription: 'Conversion Readiness Checker für Landingpages, Performance, Onpage-Basis und CRO-Vorbereitung.',
    inputMode: 'url',
    placeholder: 'https://deine-domain.de/angebot',
    buttonLabel: 'Conversion prüfen',
    categorySlug: 'anzeigen',
    icon: 'target',
    engine: 'pagespeed',
    status: 'live',
    checks: ['TTFB', 'HTML-Größe', 'Cache', 'Komprimierung'],
    related: ['landing-page-quality-checker', 'ads-landing-page-checker', 'security-check'],
  },
  {
    slug: 'ai-pr-visibility-checker',
    title: 'AI PR Visibility Checker',
    shortTitle: 'AI PR Visibility',
    headline: 'AI-PR Sichtbarkeit für Marken vorbereiten',
    description: 'Prüft technische Lesbarkeit und bereitet Quellen-, Mention- und PR-Daten als eigene Strecke vor.',
    seoDescription: 'AI PR Visibility Checker für Brand Mentions, AI Search Quellen, PR Sichtbarkeit und Citation Readiness.',
    inputMode: 'url',
    placeholder: 'https://deine-domain.de/über-uns',
    buttonLabel: 'AI-PR prüfen',
    categorySlug: 'ki-pr',
    icon: 'eye',
    engine: 'ai-visibility',
    status: 'live',
    checks: ['Brand-Seite', 'Robots', 'Textbasis', 'JSON-LD'],
    related: ['brand-entity-checker', 'source-authority-checker', 'citation-readiness-checker'],
  },
  {
    slug: 'brand-entity-checker',
    title: 'Brand Entity Checker',
    shortTitle: 'Brand Entity',
    headline: 'Marken-Entität für AI Search prüfen',
    description: 'Analysiert eingegebenen Brand-Text auf Klarheit, Begriffe und maschinenlesbare Strukturhinweise.',
    seoDescription: 'Brand Entity Checker für Markenprofil, Entitäten, AI Search, Knowledge Graph und PR Signale.',
    inputMode: 'text',
    placeholder: 'Füge Markenprofil, About-Text oder Pressebeschreibung ein',
    buttonLabel: 'Brand prüfen',
    categorySlug: 'ki-pr',
    icon: 'eye',
    engine: 'text-utility',
    status: 'live',
    checks: ['Brand-Text', 'Begriffe', 'Klarheit', 'Snippet'],
    related: ['entity-checker', 'ai-pr-visibility-checker', 'citation-readiness-checker'],
  },
  {
    slug: 'press-mention-monitor',
    title: 'Press Mention Monitor',
    shortTitle: 'Mentions',
    headline: 'Presse-Mentions als Monitoring-Strecke',
    description: 'Mentions brauchen News- und Webdatenprovider und werden vom Website-Crawl getrennt.',
    seoDescription: 'Press Mention Monitor für PR Erwahnungen, Brand Mentions, Quellen und AI PR Reporting.',
    inputMode: 'keyword',
    placeholder: 'marke oder person',
    buttonLabel: 'Mentions vorbereiten',
    categorySlug: 'ki-pr',
    icon: 'eye',
    engine: 'keyword-provider',
    status: 'provider',
    checks: ['Mentions', 'Quellen', 'PR', 'Monitoring'],
    related: ['source-authority-checker', 'ai-pr-report', 'brand-entity-checker'],
  },
  {
    slug: 'source-authority-checker',
    title: 'Source Authority Checker',
    shortTitle: 'Source Authority',
    headline: 'Quellenautorität für AI-PR vorbereiten',
    description: 'Bereitet Quellen- und Medienlisten für AI-Zitationen und PR Outreach vor.',
    seoDescription: 'Source Authority Checker für AI Search Quellen, Medienautorität, Zitationen und PR Outreach.',
    inputMode: 'url',
    placeholder: 'https://quelle-oder-medium.de',
    buttonLabel: 'Quelle vorbereiten',
    categorySlug: 'ki-pr',
    icon: 'eye',
    engine: 'url-provider',
    status: 'provider',
    checks: ['Quelle', 'Authority', 'Mentions', 'PR Fit'],
    related: ['citation-readiness-checker', 'journalist-outreach-planner', 'ai-pr-visibility-checker'],
  },
  {
    slug: 'citation-readiness-checker',
    title: 'Citation Readiness Checker',
    shortTitle: 'Citation Ready',
    headline: 'Zitatfähigkeit deiner Inhalte prüfen',
    description: 'Prüft Textstruktur, klare Aussagen und maschinenlesbare Signale als Grundlage für AI- und PR-Zitate.',
    seoDescription: 'Citation Readiness Checker für zitierbare Inhalte, klare Aussagen, AI Search und PR Quellen.',
    inputMode: 'text',
    placeholder: 'Füge den Abschnitt ein, der als Quelle funktionieren soll',
    buttonLabel: 'Citation prüfen',
    categorySlug: 'ki-pr',
    icon: 'check',
    engine: 'text-utility',
    status: 'live',
    checks: ['Aussagen', 'Klarheit', 'Länge', 'Struktur'],
    related: ['ai-snippet-checker', 'brand-entity-checker', 'source-authority-checker'],
  },
  {
    slug: 'journalist-outreach-planner',
    title: 'Journalist Outreach Planner',
    shortTitle: 'Outreach',
    headline: 'PR Outreach aus Thema und Marke planen',
    description: 'Plant Outreach-Ansatz, Themenwinkel und Briefing ohne E-Mail-Versand oder fremde Datenübertragung.',
    seoDescription: 'Journalist Outreach Planner für PR Themen, Pitches, Medienlisten und AI PR Kampagnen.',
    inputMode: 'keyword',
    placeholder: 'thema oder pr story',
    buttonLabel: 'Outreach planen',
    categorySlug: 'ki-pr',
    icon: 'megaphone',
    engine: 'keyword-local',
    status: 'live',
    checks: ['Thema', 'Pitch', 'Format', 'Nächster Schritt'],
    related: ['press-mention-monitor', 'source-authority-checker', 'ai-pr-report'],
  },
  {
    slug: 'ai-pr-report',
    title: 'AI PR Report',
    shortTitle: 'AI PR Report',
    headline: 'AI-PR Ergebnisse reportingfähig machen',
    description: 'Bereitet Brand Mentions, Quellen und AI-Sichtbarkeit als Kundenreport vor.',
    seoDescription: 'AI PR Report für Brand Mentions, Quellen, AI Visibility, PR Monitoring und Kundenreports.',
    inputMode: 'url',
    placeholder: 'https://deine-domain.de',
    buttonLabel: 'AI-PR Report vorbereiten',
    categorySlug: 'ki-pr',
    icon: 'fileText',
    engine: 'reporting',
    status: 'audit',
    checks: ['Mentions', 'Quellen', 'AI Visibility', 'Report'],
    related: ['ai-pr-visibility-checker', 'client-report-generator', 'brand-entity-checker'],
  },
  {
    slug: 'seo-report-generator',
    title: 'SEO Report Generator',
    shortTitle: 'SEO Report',
    headline: 'SEO Reports mit Planlimits und Evidence erzeugen',
    description: 'Führt Crawl-Ergebnisse, sichtbare Detailseiten, Issues, Evidence und Prioritäten in Reports zusammen.',
    seoDescription: 'SEO Report Generator für Website Audits, Planlimits, sichtbare Detailseiten, Issues, Evidence und Aufgaben.',
    inputMode: 'url',
    placeholder: 'https://deine-domain.de',
    buttonLabel: 'Report vorbereiten',
    categorySlug: 'berichte',
    icon: 'fileText',
    engine: 'reporting',
    status: 'audit',
    checks: ['Audit', 'Issues', 'Evidence', 'Prioritäten'],
    related: ['white-label-report', 'client-report-generator', 'site-audit'],
  },
  {
    slug: 'white-label-report',
    title: 'White Label Report',
    shortTitle: 'White Label',
    headline: 'White-Label Reports für Agenturen',
    description: 'Eigene Report-Strecke für Branding, Custom Domain, PDF-Export und Kundenfreigaben.',
    seoDescription: 'White Label Report Tool für Agenturen, Branding, Custom Domain, PDF Export und Kundenfreigaben.',
    inputMode: 'url',
    placeholder: 'https://kunden-domain.de',
    buttonLabel: 'White Label vorbereiten',
    categorySlug: 'berichte',
    icon: 'fileText',
    engine: 'reporting',
    status: 'audit',
    checks: ['Branding', 'Custom Domain', 'PDF', 'Freigabe'],
    related: ['client-report-generator', 'audit-export-tool', 'team-reporting-dashboard'],
  },
  {
    slug: 'client-report-generator',
    title: 'Client Report Generator',
    shortTitle: 'Client Reports',
    headline: 'Kundenreports aus Audits und Monitoring bauen',
    description: 'Bereitet klare Kundenansichten, Zusammenfassungen und Tasks für Agentur-Workflows vor.',
    seoDescription: 'Client Report Generator für Agenturberichte, Kundenansichten, SEO Reports und Monitoring Zusammenfassungen.',
    inputMode: 'url',
    placeholder: 'https://kunden-domain.de',
    buttonLabel: 'Kundenreport vorbereiten',
    categorySlug: 'berichte',
    icon: 'users',
    engine: 'reporting',
    status: 'audit',
    checks: ['Kundenansicht', 'Summary', 'Tasks', 'Monitoring'],
    related: ['white-label-report', 'seo-report-generator', 'team-reporting-dashboard'],
  },
  {
    slug: 'audit-export-tool',
    title: 'Audit Export Tool',
    shortTitle: 'Audit Export',
    headline: 'Exports für Audits, CSV und PDF vorbereiten',
    description: 'Trennt Exportrechte, Planlimits und Report-Inhalte sauber vom eigentlichen Crawl.',
    seoDescription: 'Audit Export Tool für SEO Audits, PDF Export, CSV Export, Planlimits und Kundenreports.',
    inputMode: 'url',
    placeholder: 'https://deine-domain.de',
    buttonLabel: 'Export vorbereiten',
    categorySlug: 'berichte',
    icon: 'fileText',
    engine: 'reporting',
    status: 'audit',
    checks: ['PDF', 'CSV', 'Planlimits', 'Freigaben'],
    related: ['seo-report-generator', 'white-label-report', 'evidence-screenshot-report'],
  },
  {
    slug: 'monitoring-report',
    title: 'Monitoring Report',
    shortTitle: 'Monitoring',
    headline: 'Monitoring Reports für wiederkehrende Audits',
    description: 'Führt geplante Scans, Veränderungen, Rankings und Kundenupdates als eigene Reportstrecke.',
    seoDescription: 'Monitoring Report Tool für wiederkehrende SEO Audits, Ranking Monitoring, Veränderungen und Kundenupdates.',
    inputMode: 'url',
    placeholder: 'https://deine-domain.de',
    buttonLabel: 'Monitoring vorbereiten',
    categorySlug: 'berichte',
    icon: 'chart',
    engine: 'reporting',
    status: 'audit',
    checks: ['Historie', 'Alerts', 'Scans', 'Kundenupdates'],
    related: ['rank-tracker', 'client-report-generator', 'site-audit'],
  },
  {
    slug: 'evidence-screenshot-report',
    title: 'Evidence Screenshot Report',
    shortTitle: 'Evidence',
    headline: 'Evidence-Screenshots und Belege für Reports',
    description: 'Sammelt Screenshots, Rohdaten und Beweise für Issue-URLs je nach Planlimit.',
    seoDescription: 'Evidence Screenshot Report für SEO Issues, Screenshots, Belege, Planlimits und Kundenreports.',
    inputMode: 'url',
    placeholder: 'https://deine-domain.de',
    buttonLabel: 'Evidence vorbereiten',
    categorySlug: 'berichte',
    icon: 'eye',
    engine: 'reporting',
    status: 'audit',
    checks: ['Screenshots', 'Issue-URLs', 'Evidence', 'Planlimit'],
    related: ['seo-report-generator', 'audit-export-tool', 'white-label-report'],
  },
  {
    slug: 'gsc-report',
    title: 'Google Search Console Report',
    shortTitle: 'GSC Report',
    headline: 'GSC Daten in SEO Reports integrieren',
    description: 'Bereitet Search-Console-Daten für Keywords, Klicks, Impressionen und Kundenreports vor.',
    seoDescription: 'Google Search Console Report für Klicks, Impressionen, Keywords, SEO Reports und Kundenanalysen.',
    inputMode: 'url',
    placeholder: 'https://deine-domain.de',
    buttonLabel: 'GSC Report vorbereiten',
    categorySlug: 'berichte',
    icon: 'chart',
    engine: 'reporting',
    status: 'provider',
    checks: ['Klicks', 'Impressionen', 'Keywords', 'Report'],
    related: ['seo-report-generator', 'rank-tracker', 'client-report-generator'],
  },
  {
    slug: 'team-reporting-dashboard',
    title: 'Team Reporting Dashboard',
    shortTitle: 'Team Reports',
    headline: 'Team- und Agentur-Reporting skalieren',
    description: 'Bereitet Seats, Projekte, Kundenreports und White-Label-Workflows als eigenes Agenturprodukt vor.',
    seoDescription: 'Team Reporting Dashboard für Agenturen, Seats, Projekte, Kundenreports und White Label Workflows.',
    inputMode: 'url',
    placeholder: 'https://kunden-domain.de',
    buttonLabel: 'Team-Reporting vorbereiten',
    categorySlug: 'berichte',
    icon: 'users',
    engine: 'reporting',
    status: 'audit',
    checks: ['Seats', 'Projekte', 'Kunden', 'Reports'],
    related: ['white-label-report', 'client-report-generator', 'monitoring-report'],
  },
  {
    slug: 'security-check',
    title: 'Security Header Check',
    shortTitle: 'Security',
    headline: 'Security Header für eine URL prüfen',
    description: 'Prüft HTTPS und wichtige Browser-Schutzheader wie CSP, HSTS, X-Frame-Options und Referrer-Policy.',
    seoDescription: 'Security Header Check für Websites: HTTPS, CSP, HSTS, X-Frame-Options, X-Content-Type-Options und Referrer-Policy prüfen.',
    inputMode: 'url',
    placeholder: 'https://deine-domain.de',
    buttonLabel: 'Security prüfen',
    categorySlug: 'security-dsgvo',
    icon: 'shield',
    engine: 'security',
    status: 'live',
    checks: ['HTTPS', 'CSP', 'HSTS', 'Frame-Schutz'],
    related: ['https-checker', 'cookie-consent-checker', 'dsgvo-checker'],
  },
  {
    slug: 'https-checker',
    title: 'HTTPS Checker',
    shortTitle: 'HTTPS',
    headline: 'HTTPS und sichere Auslieferung prüfen',
    description: 'Prüft, ob die Ziel-URL über HTTPS erreichbar ist und Security-Basisheader liefert.',
    seoDescription: 'HTTPS Checker für sichere Website-Auslieferung, HSTS, Security Header und Browser-Schutz.',
    inputMode: 'url',
    placeholder: 'https://deine-domain.de',
    buttonLabel: 'HTTPS prüfen',
    categorySlug: 'security-dsgvo',
    icon: 'lock',
    engine: 'security',
    status: 'live',
    checks: ['HTTPS', 'HSTS', 'Status', 'Header'],
    related: ['security-check', 'ssl-certificate-checker', 'mixed-content-checker'],
  },
  {
    slug: 'ssl-certificate-checker',
    title: 'SSL Certificate Checker',
    shortTitle: 'SSL Check',
    headline: 'SSL Zertifikat als Security-Strecke vorbereiten',
    description: 'Browser-nahe Zertifikatsdetails brauchen eigene TLS-Prüfung; Header-Basis ist sofort testbar.',
    seoDescription: 'SSL Certificate Checker für TLS, HTTPS, Zertifikat, Ablaufdaten und Website Security.',
    inputMode: 'url',
    placeholder: 'https://deine-domain.de',
    buttonLabel: 'SSL vorbereiten',
    categorySlug: 'security-dsgvo',
    icon: 'lock',
    engine: 'security',
    status: 'live',
    checks: ['HTTPS', 'HSTS', 'Zertifikat', 'Ablauf'],
    related: ['https-checker', 'security-check', 'mixed-content-checker'],
  },
  {
    slug: 'cookie-consent-checker',
    title: 'Cookie Consent Checker',
    shortTitle: 'Cookie Check',
    headline: 'Cookie Consent und Datenschutz-Hinweise prüfen',
    description: 'Bereitet Cookie-, Consent- und DSGVO-Prüfungen als eigene Compliance-Strecke vor.',
    seoDescription: 'Cookie Consent Checker für DSGVO, Consent Banner, Cookies, Datenschutz und Compliance Risiken.',
    inputMode: 'url',
    placeholder: 'https://deine-domain.de',
    buttonLabel: 'Cookie Check vorbereiten',
    categorySlug: 'security-dsgvo',
    icon: 'shield',
    engine: 'full-audit',
    status: 'audit',
    checks: ['Consent', 'Cookies', 'Datenschutz', 'Evidence'],
    related: ['dsgvo-checker', 'privacy-policy-checker', 'security-check'],
  },
  {
    slug: 'dsgvo-checker',
    title: 'DSGVO Checker',
    shortTitle: 'DSGVO',
    headline: 'DSGVO Risiken im Website Audit prüfen',
    description: 'Verbindet technische Website-Signale, Datenschutzseiten, Cookie-Hinweise und Evidence im Audit.',
    seoDescription: 'DSGVO Checker für Websites, Datenschutz, Cookies, Impressum, Consent und Compliance Evidence.',
    inputMode: 'url',
    placeholder: 'https://deine-domain.de',
    buttonLabel: 'DSGVO Audit vorbereiten',
    categorySlug: 'security-dsgvo',
    icon: 'shield',
    engine: 'full-audit',
    status: 'audit',
    checks: ['Datenschutz', 'Cookies', 'Impressum', 'Evidence'],
    related: ['cookie-consent-checker', 'privacy-policy-checker', 'compliance-report'],
  },
  {
    slug: 'privacy-policy-checker',
    title: 'Privacy Policy Checker',
    shortTitle: 'Privacy',
    headline: 'Datenschutzerklärung technisch auffindbar machen',
    description: 'Prüft im Audit, ob Datenschutzseiten, Links und Hinweise auffindbar und reportingfähig sind.',
    seoDescription: 'Privacy Policy Checker für Datenschutzerklärung, Datenschutzlinks, Compliance und Website Audits.',
    inputMode: 'url',
    placeholder: 'https://deine-domain.de',
    buttonLabel: 'Privacy Check vorbereiten',
    categorySlug: 'security-dsgvo',
    icon: 'fileText',
    engine: 'full-audit',
    status: 'audit',
    checks: ['Datenschutzseite', 'Links', 'Status', 'Evidence'],
    related: ['dsgvo-checker', 'cookie-consent-checker', 'compliance-report'],
  },
  {
    slug: 'accessibility-checker',
    title: 'Accessibility Checker',
    shortTitle: 'Accessibility',
    headline: 'Accessibility und UX-Barrieren prüfen',
    description: 'Bereitet Accessibility-Prüfungen, Alt-Texte, Kontrast und Semantik im Audit als eigene Seite auf.',
    seoDescription: 'Accessibility Checker für Barrierefreiheit, Alt-Texte, Semantik, Kontrast und Website UX.',
    inputMode: 'url',
    placeholder: 'https://deine-domain.de',
    buttonLabel: 'Accessibility vorbereiten',
    categorySlug: 'security-dsgvo',
    icon: 'check',
    engine: 'full-audit',
    status: 'audit',
    checks: ['Alt-Texte', 'Semantik', 'Kontrast', 'Evidence'],
    related: ['compliance-report', 'site-audit', 'performance-audit'],
  },
  {
    slug: 'compliance-report',
    title: 'Compliance Report',
    shortTitle: 'Compliance',
    headline: 'Compliance Reports für Website-Risiken',
    description: 'Führt DSGVO, Security, Accessibility und Evidence in einem reportfähigen Compliance-Bereich zusammen.',
    seoDescription: 'Compliance Report für DSGVO, Security, Accessibility, Cookies, Evidence und Kundenberichte.',
    inputMode: 'url',
    placeholder: 'https://deine-domain.de',
    buttonLabel: 'Compliance vorbereiten',
    categorySlug: 'security-dsgvo',
    icon: 'shield',
    engine: 'reporting',
    status: 'audit',
    checks: ['DSGVO', 'Security', 'Accessibility', 'Evidence'],
    related: ['dsgvo-checker', 'security-check', 'accessibility-checker'],
  },
  {
    slug: 'pagespeed-test',
    title: 'PageSpeed Test',
    shortTitle: 'PageSpeed',
    headline: 'Schneller Performance-Test ohne Lighthouse-Kosten',
    description: 'Misst TTFB, Antwortgröße, Komprimierung und Cache-Hinweise für eine einzelne URL.',
    seoDescription: 'PageSpeed Test für eine einzelne URL: TTFB, HTML-Größe, Komprimierung und Cache-Hinweise ohne Website-Crawl prüfen.',
    inputMode: 'url',
    placeholder: 'https://deine-domain.de',
    buttonLabel: 'Performance prüfen',
    categorySlug: 'performance-technik',
    icon: 'zap',
    engine: 'pagespeed',
    status: 'live',
    checks: ['TTFB', 'Antwortgröße', 'Komprimierung', 'Cache-Header'],
    related: ['core-web-vitals-checker', 'performance-audit', 'rendering-checker'],
  },
  {
    slug: 'core-web-vitals-checker',
    title: 'Core Web Vitals Checker',
    shortTitle: 'Core Web Vitals',
    headline: 'Core-Web-Vitals-nahe Signale vorbereiten',
    description: 'Prüft schnelle Server- und HTML-Signale; echte Felddaten können über CrUX/PSI angebunden werden.',
    seoDescription: 'Core Web Vitals Checker für Performance, TTFB, PSI, CrUX, LCP, CLS und INP Vorbereitung.',
    inputMode: 'url',
    placeholder: 'https://deine-domain.de',
    buttonLabel: 'Vitals vorbereiten',
    categorySlug: 'performance-technik',
    icon: 'zap',
    engine: 'pagespeed',
    status: 'live',
    checks: ['TTFB', 'HTML-Größe', 'Cache', 'CrUX Ready'],
    related: ['pagespeed-test', 'performance-audit', 'image-optimization-checker'],
  },
  {
    slug: 'performance-audit',
    title: 'Performance Audit',
    shortTitle: 'Performance Audit',
    headline: 'Performance im Full Audit priorisieren',
    description: 'Verbindet schnelle Checks, Lighthouse-nahe Signale, Ressourcen und Aufgaben in einem Audit.',
    seoDescription: 'Performance Audit für PageSpeed, Core Web Vitals, Ressourcen, Lighthouse-nahe Checks und Prioritäten.',
    inputMode: 'url',
    placeholder: 'https://deine-domain.de',
    buttonLabel: 'Performance Audit vorbereiten',
    categorySlug: 'performance-technik',
    icon: 'zap',
    engine: 'full-audit',
    status: 'audit',
    checks: ['Ressourcen', 'Lighthouse', 'Tasks', 'Evidence'],
    related: ['pagespeed-test', 'core-web-vitals-checker', 'site-audit'],
  },
  {
    slug: 'redirect-chain-checker',
    title: 'Redirect Chain Checker',
    shortTitle: 'Redirects',
    headline: 'Redirect Chains als technische Audit-Strecke',
    description: 'Redirect-Ketten und Statuscode-Verteilungen werden im Crawl gesammelt und reportingfähig gemacht.',
    seoDescription: 'Redirect Chain Checker für Weiterleitungsketten, Statuscodes, technische SEO und Crawl Audits.',
    inputMode: 'url',
    placeholder: 'https://deine-domain.de',
    buttonLabel: 'Redirect Audit vorbereiten',
    categorySlug: 'performance-technik',
    icon: 'link',
    engine: 'full-audit',
    status: 'audit',
    checks: ['Weiterleitungen', 'Statuscodes', 'Ketten', 'Crawl'],
    related: ['broken-link-checker', 'technical-seo-audit', 'http-status-checker'],
  },
  {
    slug: 'http-status-checker',
    title: 'HTTP Status Checker',
    shortTitle: 'HTTP Status',
    headline: 'HTTP Status einer URL schnell prüfen',
    description: 'Prüft Erreichbarkeit und Basisstatus ohne Crawl und ohne Report-Erzeugung.',
    seoDescription: 'HTTP Status Checker für URL Status, Erreichbarkeit, Weiterleitungen und technische Website Checks.',
    inputMode: 'url',
    placeholder: 'https://deine-domain.de/seite',
    buttonLabel: 'Status prüfen',
    categorySlug: 'performance-technik',
    icon: 'terminal',
    engine: 'pagespeed',
    status: 'live',
    checks: ['HTTP Status', 'TTFB', 'Größe', 'Cache'],
    related: ['redirect-chain-checker', 'security-check', 'pagespeed-test'],
  },
  {
    slug: 'rendering-checker',
    title: 'Rendering Checker',
    shortTitle: 'Rendering',
    headline: 'Rendering und Fetch-vs-Browser Audits vorbereiten',
    description: 'Trennt einfache Fetch-Checks von browserbasierten Render-Audits mit höheren Kosten.',
    seoDescription: 'Rendering Checker für JavaScript Websites, Fetch vs Browser Rendering, SEO Audits und Kostenkontrolle.',
    inputMode: 'url',
    placeholder: 'https://deine-domain.de/app',
    buttonLabel: 'Rendering vorbereiten',
    categorySlug: 'performance-technik',
    icon: 'eye',
    engine: 'full-audit',
    status: 'audit',
    checks: ['Fetch', 'Browser', 'DOM Diff', 'Kostenkontrolle'],
    related: ['performance-audit', 'technical-seo-audit', 'ai-visibility-checker'],
  },
  {
    slug: 'image-optimization-checker',
    title: 'Image Optimization Checker',
    shortTitle: 'Images',
    headline: 'Bildoptimierung im Performance Audit prüfen',
    description: 'Bildgrößen, Alt-Texte und Ressourcen werden im Crawl mit Evidence gesammelt.',
    seoDescription: 'Image Optimization Checker für Bildgrößen, Alt-Texte, Performance, SEO und Accessibility.',
    inputMode: 'url',
    placeholder: 'https://deine-domain.de',
    buttonLabel: 'Image Audit vorbereiten',
    categorySlug: 'performance-technik',
    icon: 'fileText',
    engine: 'full-audit',
    status: 'audit',
    checks: ['Bildgrößen', 'Alt-Texte', 'Lazy Loading', 'Evidence'],
    related: ['performance-audit', 'accessibility-checker', 'core-web-vitals-checker'],
  },
  {
    slug: 'mixed-content-checker',
    title: 'Mixed Content Checker',
    shortTitle: 'Mixed Content',
    headline: 'Mixed Content und unsichere Ressourcen finden',
    description: 'Mixed Content wird über technische Audits und Ressourcenlisten statt einzelner Header-Checks gefunden.',
    seoDescription: 'Mixed Content Checker für HTTPS, unsichere Ressourcen, Security Audits und Website Technik.',
    inputMode: 'url',
    placeholder: 'https://deine-domain.de',
    buttonLabel: 'Mixed Content vorbereiten',
    categorySlug: 'performance-technik',
    icon: 'lock',
    engine: 'full-audit',
    status: 'audit',
    checks: ['HTTPS', 'Ressourcen', 'Security', 'Evidence'],
    related: ['https-checker', 'security-check', 'performance-audit'],
  },
];

export const TOOL_PAGES: ToolPage[] = TOOL_DEFINITIONS.map((tool) => ({
  ...tool,
  category: categoryTitleBySlug.get(tool.categorySlug) || tool.categorySlug,
}));

export const TOOL_PAGE_MAP = new Map(TOOL_PAGES.map((page) => [page.slug, page]));
export const TOOL_CATEGORY_MAP = new Map(TOOL_CATEGORIES.map((category) => [category.slug, category]));

export function getToolPage(slug: string) {
  return TOOL_PAGE_MAP.get(slug);
}

export function getToolCategory(slug: string) {
  return TOOL_CATEGORY_MAP.get(slug as ToolCategorySlug);
}

export function getToolsForCategory(slug: ToolCategorySlug) {
  return TOOL_PAGES.filter((tool) => tool.categorySlug === slug);
}

export function isToolSlug(slug: string): slug is ToolSlug {
  return TOOL_PAGE_MAP.has(slug);
}

export function isToolCategorySlug(slug: string): slug is ToolCategorySlug {
  return TOOL_CATEGORY_MAP.has(slug as ToolCategorySlug);
}
